// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: Stellar.proto

package stellar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional in case of non-native asset; the asset issuer address
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Optional in case of non-native asset; the asset alphanum4 code.
	Alphanum4 string `protobuf:"bytes,2,opt,name=alphanum4,proto3" json:"alphanum4,omitempty"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Asset) GetAlphanum4() string {
	if x != nil {
		return x.Alphanum4
	}
	return ""
}

type OperationCreateAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// Amount (*10^7)
	Amount int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *OperationCreateAccount) Reset() {
	*x = OperationCreateAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationCreateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationCreateAccount) ProtoMessage() {}

func (x *OperationCreateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationCreateAccount.ProtoReflect.Descriptor instead.
func (*OperationCreateAccount) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{1}
}

func (x *OperationCreateAccount) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *OperationCreateAccount) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OperationPayment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// Optional, can be left empty for native asset
	Asset *Asset `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	// Amount (*10^7)
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *OperationPayment) Reset() {
	*x = OperationPayment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationPayment) ProtoMessage() {}

func (x *OperationPayment) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationPayment.ProtoReflect.Descriptor instead.
func (*OperationPayment) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{2}
}

func (x *OperationPayment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *OperationPayment) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *OperationPayment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OperationChangeTrust struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Validity (time bound to), unix time.  Set to (now() + 2 * 365 * 86400) for 2 years; set to 0 for missing.
	ValidBefore int64 `protobuf:"varint,2,opt,name=valid_before,json=validBefore,proto3" json:"valid_before,omitempty"`
}

func (x *OperationChangeTrust) Reset() {
	*x = OperationChangeTrust{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationChangeTrust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationChangeTrust) ProtoMessage() {}

func (x *OperationChangeTrust) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationChangeTrust.ProtoReflect.Descriptor instead.
func (*OperationChangeTrust) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{3}
}

func (x *OperationChangeTrust) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *OperationChangeTrust) GetValidBefore() int64 {
	if x != nil {
		return x.ValidBefore
	}
	return 0
}

type MemoVoid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MemoVoid) Reset() {
	*x = MemoVoid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoVoid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoVoid) ProtoMessage() {}

func (x *MemoVoid) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoVoid.ProtoReflect.Descriptor instead.
func (*MemoVoid) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{4}
}

type MemoText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *MemoText) Reset() {
	*x = MemoText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoText) ProtoMessage() {}

func (x *MemoText) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoText.ProtoReflect.Descriptor instead.
func (*MemoText) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{5}
}

func (x *MemoText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MemoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MemoId) Reset() {
	*x = MemoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoId) ProtoMessage() {}

func (x *MemoId) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoId.ProtoReflect.Descriptor instead.
func (*MemoId) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{6}
}

func (x *MemoId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MemoHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *MemoHash) Reset() {
	*x = MemoHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoHash) ProtoMessage() {}

func (x *MemoHash) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoHash.ProtoReflect.Descriptor instead.
func (*MemoHash) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{7}
}

func (x *MemoHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Input data necessary to create a signed transaction.
type SigningInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fee      int32  `protobuf:"varint,1,opt,name=fee,proto3" json:"fee,omitempty"`
	Sequence int64  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Account  string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// Private key.
	PrivateKey []byte `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Passphrase string `protobuf:"bytes,5,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	// Types that are assignable to OperationOneof:
	//	*SigningInput_OpCreateAccount
	//	*SigningInput_OpPayment
	//	*SigningInput_OpChangeTrust
	OperationOneof isSigningInput_OperationOneof `protobuf_oneof:"operation_oneof"`
	// Types that are assignable to MemoTypeOneof:
	//	*SigningInput_MemoVoid
	//	*SigningInput_MemoText
	//	*SigningInput_MemoId
	//	*SigningInput_MemoHash
	//	*SigningInput_MemoReturnHash
	MemoTypeOneof isSigningInput_MemoTypeOneof `protobuf_oneof:"memo_type_oneof"`
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{8}
}

func (x *SigningInput) GetFee() int32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *SigningInput) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SigningInput) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SigningInput) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *SigningInput) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (m *SigningInput) GetOperationOneof() isSigningInput_OperationOneof {
	if m != nil {
		return m.OperationOneof
	}
	return nil
}

func (x *SigningInput) GetOpCreateAccount() *OperationCreateAccount {
	if x, ok := x.GetOperationOneof().(*SigningInput_OpCreateAccount); ok {
		return x.OpCreateAccount
	}
	return nil
}

func (x *SigningInput) GetOpPayment() *OperationPayment {
	if x, ok := x.GetOperationOneof().(*SigningInput_OpPayment); ok {
		return x.OpPayment
	}
	return nil
}

func (x *SigningInput) GetOpChangeTrust() *OperationChangeTrust {
	if x, ok := x.GetOperationOneof().(*SigningInput_OpChangeTrust); ok {
		return x.OpChangeTrust
	}
	return nil
}

func (m *SigningInput) GetMemoTypeOneof() isSigningInput_MemoTypeOneof {
	if m != nil {
		return m.MemoTypeOneof
	}
	return nil
}

func (x *SigningInput) GetMemoVoid() *MemoVoid {
	if x, ok := x.GetMemoTypeOneof().(*SigningInput_MemoVoid); ok {
		return x.MemoVoid
	}
	return nil
}

func (x *SigningInput) GetMemoText() *MemoText {
	if x, ok := x.GetMemoTypeOneof().(*SigningInput_MemoText); ok {
		return x.MemoText
	}
	return nil
}

func (x *SigningInput) GetMemoId() *MemoId {
	if x, ok := x.GetMemoTypeOneof().(*SigningInput_MemoId); ok {
		return x.MemoId
	}
	return nil
}

func (x *SigningInput) GetMemoHash() *MemoHash {
	if x, ok := x.GetMemoTypeOneof().(*SigningInput_MemoHash); ok {
		return x.MemoHash
	}
	return nil
}

func (x *SigningInput) GetMemoReturnHash() *MemoHash {
	if x, ok := x.GetMemoTypeOneof().(*SigningInput_MemoReturnHash); ok {
		return x.MemoReturnHash
	}
	return nil
}

type isSigningInput_OperationOneof interface {
	isSigningInput_OperationOneof()
}

type SigningInput_OpCreateAccount struct {
	OpCreateAccount *OperationCreateAccount `protobuf:"bytes,6,opt,name=op_create_account,json=opCreateAccount,proto3,oneof"`
}

type SigningInput_OpPayment struct {
	OpPayment *OperationPayment `protobuf:"bytes,7,opt,name=op_payment,json=opPayment,proto3,oneof"`
}

type SigningInput_OpChangeTrust struct {
	OpChangeTrust *OperationChangeTrust `protobuf:"bytes,8,opt,name=op_change_trust,json=opChangeTrust,proto3,oneof"`
}

func (*SigningInput_OpCreateAccount) isSigningInput_OperationOneof() {}

func (*SigningInput_OpPayment) isSigningInput_OperationOneof() {}

func (*SigningInput_OpChangeTrust) isSigningInput_OperationOneof() {}

type isSigningInput_MemoTypeOneof interface {
	isSigningInput_MemoTypeOneof()
}

type SigningInput_MemoVoid struct {
	MemoVoid *MemoVoid `protobuf:"bytes,9,opt,name=memo_void,json=memoVoid,proto3,oneof"`
}

type SigningInput_MemoText struct {
	MemoText *MemoText `protobuf:"bytes,10,opt,name=memo_text,json=memoText,proto3,oneof"`
}

type SigningInput_MemoId struct {
	MemoId *MemoId `protobuf:"bytes,11,opt,name=memo_id,json=memoId,proto3,oneof"`
}

type SigningInput_MemoHash struct {
	MemoHash *MemoHash `protobuf:"bytes,12,opt,name=memo_hash,json=memoHash,proto3,oneof"`
}

type SigningInput_MemoReturnHash struct {
	MemoReturnHash *MemoHash `protobuf:"bytes,13,opt,name=memo_return_hash,json=memoReturnHash,proto3,oneof"`
}

func (*SigningInput_MemoVoid) isSigningInput_MemoTypeOneof() {}

func (*SigningInput_MemoText) isSigningInput_MemoTypeOneof() {}

func (*SigningInput_MemoId) isSigningInput_MemoTypeOneof() {}

func (*SigningInput_MemoHash) isSigningInput_MemoTypeOneof() {}

func (*SigningInput_MemoReturnHash) isSigningInput_MemoTypeOneof() {}

// Transaction signing output.
type SigningOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Signature.
	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Stellar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_Stellar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_Stellar_proto_rawDescGZIP(), []int{9}
}

func (x *SigningOutput) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_Stellar_proto protoreflect.FileDescriptor

var file_Stellar_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x53, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x54, 0x57, 0x2e, 0x53, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3d, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x6e, 0x75, 0x6d, 0x34, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x6e, 0x75, 0x6d, 0x34,
	0x22, 0x52, 0x0a, 0x16, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x7b, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x57, 0x2e, 0x53,
	0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x68, 0x0a, 0x14, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x57, 0x2e, 0x53, 0x74,
	0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x4d,
	0x65, 0x6d, 0x6f, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x08, 0x4d, 0x65, 0x6d, 0x6f, 0x54,
	0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x18, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x6f, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x1e, 0x0a, 0x08, 0x4d, 0x65, 0x6d, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x22, 0xda, 0x05, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x66, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x61, 0x73, 0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x61, 0x73, 0x73, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x6f,
	0x70, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x54, 0x57, 0x2e, 0x53, 0x74, 0x65, 0x6c,
	0x6c, 0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x0f, 0x6f, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x43, 0x0a, 0x0a, 0x6f, 0x70, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x54, 0x57, 0x2e, 0x53, 0x74, 0x65,
	0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6f,
	0x70, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x50, 0x0a, 0x0f, 0x6f, 0x70, 0x5f, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x54, 0x57, 0x2e, 0x53, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x6f, 0x70, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x6d, 0x65,
	0x6d, 0x6f, 0x5f, 0x76, 0x6f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x54, 0x57, 0x2e, 0x53, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x56, 0x6f, 0x69, 0x64, 0x48, 0x01, 0x52, 0x08, 0x6d, 0x65, 0x6d,
	0x6f, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x5f, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x54, 0x57, 0x2e, 0x53, 0x74,
	0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x6f,
	0x54, 0x65, 0x78, 0x74, 0x48, 0x01, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x33, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x54, 0x57, 0x2e, 0x53, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x49, 0x64, 0x48, 0x01, 0x52, 0x06, 0x6d,
	0x65, 0x6d, 0x6f, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x54, 0x57, 0x2e, 0x53, 0x74,
	0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x6f,
	0x48, 0x61, 0x73, 0x68, 0x48, 0x01, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x46, 0x0a, 0x10, 0x6d, 0x65, 0x6d, 0x6f, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x54, 0x57, 0x2e,
	0x53, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65,
	0x6d, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x48, 0x01, 0x52, 0x0e, 0x6d, 0x65, 0x6d, 0x6f, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x42, 0x11, 0x0a, 0x0f, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x11, 0x0a, 0x0f, 0x6d,
	0x65, 0x6d, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x2d,
	0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x3c, 0x0a,
	0x15, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6a, 0x6e, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x23, 0x61, 0x6c, 0x66, 0x61, 0x63, 0x61, 0x73, 0x68,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Stellar_proto_rawDescOnce sync.Once
	file_Stellar_proto_rawDescData = file_Stellar_proto_rawDesc
)

func file_Stellar_proto_rawDescGZIP() []byte {
	file_Stellar_proto_rawDescOnce.Do(func() {
		file_Stellar_proto_rawDescData = protoimpl.X.CompressGZIP(file_Stellar_proto_rawDescData)
	})
	return file_Stellar_proto_rawDescData
}

var file_Stellar_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Stellar_proto_goTypes = []interface{}{
	(*Asset)(nil),                  // 0: TW.Stellar.Proto.Asset
	(*OperationCreateAccount)(nil), // 1: TW.Stellar.Proto.OperationCreateAccount
	(*OperationPayment)(nil),       // 2: TW.Stellar.Proto.OperationPayment
	(*OperationChangeTrust)(nil),   // 3: TW.Stellar.Proto.OperationChangeTrust
	(*MemoVoid)(nil),               // 4: TW.Stellar.Proto.MemoVoid
	(*MemoText)(nil),               // 5: TW.Stellar.Proto.MemoText
	(*MemoId)(nil),                 // 6: TW.Stellar.Proto.MemoId
	(*MemoHash)(nil),               // 7: TW.Stellar.Proto.MemoHash
	(*SigningInput)(nil),           // 8: TW.Stellar.Proto.SigningInput
	(*SigningOutput)(nil),          // 9: TW.Stellar.Proto.SigningOutput
}
var file_Stellar_proto_depIdxs = []int32{
	0,  // 0: TW.Stellar.Proto.OperationPayment.asset:type_name -> TW.Stellar.Proto.Asset
	0,  // 1: TW.Stellar.Proto.OperationChangeTrust.asset:type_name -> TW.Stellar.Proto.Asset
	1,  // 2: TW.Stellar.Proto.SigningInput.op_create_account:type_name -> TW.Stellar.Proto.OperationCreateAccount
	2,  // 3: TW.Stellar.Proto.SigningInput.op_payment:type_name -> TW.Stellar.Proto.OperationPayment
	3,  // 4: TW.Stellar.Proto.SigningInput.op_change_trust:type_name -> TW.Stellar.Proto.OperationChangeTrust
	4,  // 5: TW.Stellar.Proto.SigningInput.memo_void:type_name -> TW.Stellar.Proto.MemoVoid
	5,  // 6: TW.Stellar.Proto.SigningInput.memo_text:type_name -> TW.Stellar.Proto.MemoText
	6,  // 7: TW.Stellar.Proto.SigningInput.memo_id:type_name -> TW.Stellar.Proto.MemoId
	7,  // 8: TW.Stellar.Proto.SigningInput.memo_hash:type_name -> TW.Stellar.Proto.MemoHash
	7,  // 9: TW.Stellar.Proto.SigningInput.memo_return_hash:type_name -> TW.Stellar.Proto.MemoHash
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_Stellar_proto_init() }
func file_Stellar_proto_init() {
	if File_Stellar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Stellar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Stellar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationCreateAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Stellar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationPayment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Stellar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationChangeTrust); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Stellar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoVoid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Stellar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Stellar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Stellar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Stellar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Stellar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Stellar_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*SigningInput_OpCreateAccount)(nil),
		(*SigningInput_OpPayment)(nil),
		(*SigningInput_OpChangeTrust)(nil),
		(*SigningInput_MemoVoid)(nil),
		(*SigningInput_MemoText)(nil),
		(*SigningInput_MemoId)(nil),
		(*SigningInput_MemoHash)(nil),
		(*SigningInput_MemoReturnHash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Stellar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Stellar_proto_goTypes,
		DependencyIndexes: file_Stellar_proto_depIdxs,
		MessageInfos:      file_Stellar_proto_msgTypes,
	}.Build()
	File_Stellar_proto = out.File
	file_Stellar_proto_rawDesc = nil
	file_Stellar_proto_goTypes = nil
	file_Stellar_proto_depIdxs = nil
}
